FROM tomcat:9.0

#for save some time, so following codes are commented out first

#RUN apt-get update
#RUN apt-get install -y apt-utils
#RUN apt-get install -y net-tools
#RUN cd /tmp && netstat > netstat.log
COPY *.war /usr/local/tomcat/webapps
