apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-tomcat-nginx
spec:
  selector:    #this is selector of the deploy
    matchLabels:
      app: label-tomcat-nginx  
  replicas: 1 # tells deployment to run 3 pods matching the template
  
  template:
    metadata:
      labels:
        app: label-tomcat-nginx
    spec:
      containers:
      - name: container-name-nginx
        #image: nginx:1.14.2
        image: devopstrainer/deploy:v1
        ports:
        - containerPort: 80

      - name: container-name-tomcat
        image: tomcat:9.0
        ports:
        - containerPort: 8080
